"""扩展主流工具清单（国内外常用）—— 由 mainstream_registry.py 拆分（P2-16）。"""
from typing import Any, Dict, List

from mainstream_registry_data import _entry


EXTRA_MAINSTREAM_TOOLS: List[Dict[str, Any]] = [
    # ==== 国内常用 ====
    _entry("通义灵码", type_="IDE Plugin",
           app_bundles=["/Applications/Tongyi Lingma.app"], commands=["lingma"],
           config_paths=["~/.lingma/mcp.json", "~/.qoder/settings.json"],
           skills_path="~/.lingma/skills",
           mcp_config_path="~/.qoder/settings.json", mcp_format="json", mcp_key_path="mcpServers",
           aliases=["lingma", "tongyi-lingma", "qoder"],
           by_os={
               "windows": {
                   "app_bundles": ["%LOCALAPPDATA%\\Programs\\Qoder"],
                   "commands": ["qoder", "lingma"],
                   "config_paths": ["%USERPROFILE%\\.qoder\\settings.json"],
                   "skills_path": "%USERPROFILE%\\.qoder\\skills",
                   "mcp_config_path": "%USERPROFILE%\\.qoder\\settings.json",
               },
               "linux": {
                   "app_bundles": [],
                   "commands": ["qoder", "lingma"],
                   "config_paths": ["~/.qoder/settings.json"],
                   "skills_path": "~/.qoder/skills",
                   "mcp_config_path": "~/.qoder/settings.json",
               },
           }),
    _entry("百度 Comate", type_="IDE Plugin",
           app_bundles=["/Applications/Comate.app"], commands=["comate"],
           config_paths=["~/.comate/mcp.json"],
           aliases=["comate", "baidu-comate"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["comate"], "config_paths": ["%USERPROFILE%\\.comate\\mcp.json"]},
               "linux": {"app_bundles": [], "commands": ["comate"], "config_paths": ["~/.comate/mcp.json"]},
           }),
    _entry("CodeBuddy", type_="AI Agent",
           app_bundles=["/Applications/CodeBuddy.app"], commands=["codebuddy"],
           config_paths=["~/.codebuddy/mcp.json"], skills_path="~/.codebuddy/skills",
           mcp_config_path="~/.codebuddy/mcp.json",
           aliases=["codebuddy", "tencent-codebuddy"],
           by_os={
               "windows": {
                   "app_bundles": ["%LOCALAPPDATA%\\Programs\\CodeBuddy"],
                   "commands": ["codebuddy", "buddycn"],
                   "config_paths": ["%USERPROFILE%\\.codebuddy\\settings.json", "%USERPROFILE%\\.codebuddy\\models.json"],
                   "skills_path": "%USERPROFILE%\\.codebuddy\\skills",
                   "mcp_config_path": "%USERPROFILE%\\.codebuddy\\mcp.json",
               },
               "linux": {
                   "app_bundles": [],
                   "commands": ["codebuddy", "buddycn"],
                   "config_paths": ["~/.codebuddy/settings.json", "~/.codebuddy/models.json"],
                   "skills_path": "~/.codebuddy/skills",
                   "mcp_config_path": "~/.codebuddy/mcp.json",
               },
           }),
    _entry("Kimi", type_="AI Agent",
           app_bundles=["/Applications/Kimi.app"], commands=["kimi"],
           config_paths=["~/.kimi/mcp.json"], skills_path="~/.kimi/skills",
           aliases=["kimi", "moonshot"],
           by_os={
               "windows": {"app_bundles": ["%LOCALAPPDATA%\\Programs\\Kimi"], "commands": ["kimi"],
                           "config_paths": ["%USERPROFILE%\\.kimi\\mcp.json"], "skills_path": "%USERPROFILE%\\.kimi\\skills"},
               "linux": {"app_bundles": [], "commands": ["kimi"],
                         "config_paths": ["~/.kimi/mcp.json"], "skills_path": "~/.kimi/skills"},
           }),
    _entry("Qwen", type_="AI Agent",
           app_bundles=["/Applications/Qwen.app"], commands=["qwen"],
           config_paths=["~/.qwen/mcp.json"], skills_path="~/.qwen/skills",
           aliases=["qwen", "tongyi-qianwen"],
           by_os={
               "windows": {"app_bundles": ["%LOCALAPPDATA%\\Programs\\Qwen"], "commands": ["qwen"],
                           "config_paths": ["%USERPROFILE%\\.qwen\\mcp.json"], "skills_path": "%USERPROFILE%\\.qwen\\skills"},
               "linux": {"app_bundles": [], "commands": ["qwen"],
                         "config_paths": ["~/.qwen/mcp.json"], "skills_path": "~/.qwen/skills"},
           }),
    _entry("豆包", type_="AI Agent",
           app_bundles=["/Applications/Doubao.app"], commands=["doubao"],
           config_paths=["~/.doubao/mcp.json"],
           aliases=["doubao", "bytedance-doubao"],
           by_os={
               "windows": {"app_bundles": ["%LOCALAPPDATA%\\Doubao"], "commands": [],
                           "config_paths": ["%LOCALAPPDATA%\\Doubao"]},
               "linux": {"app_bundles": [], "commands": [], "config_paths": []},
           }),
    # QwenWork（千问办公）：仅 macOS / Windows / HarmonyOS，无 Linux 桌面版；
    # MCP 走 GUI 录入口，未公开落盘文件 → 不声明 mcp_config_path（P-5/B-8）。
    _entry("QwenWork", type_="AI Assistant",
           app_bundles=["/Applications/QwenWork.app"], commands=[],
           config_paths=["~/.qwenworkcn"],
           skills_path="~/.qwenworkcn/skills",
           aliases=["qwenwork", "qwenoffice", "千问办公"],
           by_os={
               "windows": {"app_bundles": [], "commands": [],
                           "config_paths": ["%USERPROFILE%\\.qwenworkcn"],
                           "skills_path": "%USERPROFILE%\\.qwenworkcn\\skills"},
               "linux": {"app_bundles": [], "commands": [], "config_paths": []},
           }),
    # TraeWork（字节 AI 工作台，前身 TraeCode SOLO）：桌面版仅 macOS/Windows；
    # MCP 走 GUI 录入口，未公开本地文件 → 不声明 mcp_config_path（P-5/B-8）。
    _entry("TraeWork", type_="AI Assistant",
           app_bundles=["/Applications/TraeWork.app"], commands=[],
           config_paths=["~/.trae-cn"],
           skills_path="~/.trae-cn/skills",
           aliases=["traework", "traecode", "trae-cn"],
           by_os={
               "windows": {"app_bundles": [], "commands": [],
                           "config_paths": ["%USERPROFILE%\\.trae-cn"],
                           "skills_path": "%USERPROFILE%\\.trae-cn\\skills"},
               "linux": {"app_bundles": [], "commands": [], "config_paths": []},
           }),
    _entry("Huawei CodeArts", type_="IDE Plugin",
           commands=["codearts"], config_paths=["~/.codearts/mcp.json"],
           aliases=["codearts", "huawei-codearts"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["codearts"], "config_paths": ["%USERPROFILE%\\.codearts\\mcp.json"]},
               "linux": {"app_bundles": [], "commands": ["codearts"], "config_paths": ["~/.codearts/mcp.json"]},
           }),
    _entry("DeepSeek", type_="AI Agent",
           app_bundles=["/Applications/DeepSeek.app"], commands=["deepseek"],
           config_paths=["~/.deepseek/mcp.json"], skills_path="~/.deepseek/skills",
           aliases=["deepseek", "deepseek-app"],
           by_os={
               "windows": {"app_bundles": ["%LOCALAPPDATA%\\Programs\\DeepSeek"], "commands": ["deepseek"],
                           "config_paths": ["%USERPROFILE%\\.deepseek\\mcp.json"], "skills_path": "%USERPROFILE%\\.deepseek\\skills"},
               "linux": {"app_bundles": [], "commands": ["deepseek"],
                         "config_paths": ["~/.deepseek/mcp.json"], "skills_path": "~/.deepseek/skills"},
           }),
    # ==== 国际常用 ====
    _entry("GitHub Copilot", type_="IDE Plugin",
           app_bundles=["/Applications/GitHub Copilot.app"], commands=["copilot"],
           config_paths=["~/.copilot/mcp.json", "~/.config/github-copilot/mcp.json"],
           skills_path="~/.copilot/skills", mcp_config_path="~/.copilot/mcp.json",
           aliases=["copilot", "github-copilot"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["copilot"],
                           "config_paths": ["%USERPROFILE%\\.copilot\\mcp.json"], "skills_path": "%USERPROFILE%\\.copilot\\skills"},
               "linux": {"app_bundles": [], "commands": ["copilot"],
                         "config_paths": ["~/.copilot/mcp.json"], "skills_path": "~/.copilot/skills"},
           }),
    _entry("Amazon Q", type_="IDE Plugin",
           commands=["q"], config_paths=["~/.aws/amazonq/mcp.json"],
           aliases=["amazon-q", "q-developer"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["q"], "config_paths": ["%USERPROFILE%\\.aws\\amazonq\\mcp.json"]},
               "linux": {"app_bundles": [], "commands": ["q"], "config_paths": ["~/.aws/amazonq/mcp.json"]},
           }),
    _entry("Tabnine", type_="IDE Plugin",
           commands=["tabnine"], config_paths=["~/.tabnine/mcp.json"],
           aliases=["tabnine"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["tabnine"], "config_paths": ["%USERPROFILE%\\.tabnine\\mcp.json"]},
               "linux": {"app_bundles": [], "commands": ["tabnine"], "config_paths": ["~/.tabnine/mcp.json"]},
           }),
    _entry("Cody", type_="IDE Plugin",
           commands=["cody"], config_paths=["~/.sourcegraph/cody/mcp.json"],
           skills_path="~/.sourcegraph/cody/skills",
           aliases=["cody", "sourcegraph-cody"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["cody"],
                           "config_paths": ["%USERPROFILE%\\.sourcegraph\\cody\\mcp.json"], "skills_path": "%USERPROFILE%\\.sourcegraph\\cody\\skills"},
               "linux": {"app_bundles": [], "commands": ["cody"],
                         "config_paths": ["~/.sourcegraph/cody/mcp.json"], "skills_path": "~/.sourcegraph/cody/skills"},
           }),
    _entry("Continue", type_="IDE Plugin",
           commands=["continue"], config_paths=["~/.continue/config.json"],
           skills_path="~/.continue/skills",
           aliases=["continue", "continue-dev"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["continue"],
                           "config_paths": ["%USERPROFILE%\\.continue\\config.json"], "skills_path": "%USERPROFILE%\\.continue\\skills"},
               "linux": {"app_bundles": [], "commands": ["continue"],
                         "config_paths": ["~/.continue/config.json"], "skills_path": "~/.continue/skills"},
           }),
    _entry("Augment Code", type_="IDE Plugin",
           commands=["augment"], config_paths=["~/.augment/mcp.json"],
           skills_path="~/.augment/skills",
           aliases=["augment", "augment-code"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["augment"],
                           "config_paths": ["%USERPROFILE%\\.augment\\mcp.json"], "skills_path": "%USERPROFILE%\\.augment\\skills"},
               "linux": {"app_bundles": [], "commands": ["augment"],
                         "config_paths": ["~/.augment/mcp.json"], "skills_path": "~/.augment/skills"},
           }),
    _entry("Codeium", type_="IDE Plugin",
           app_bundles=["/Applications/Codeium.app"], commands=["codeium"],
           config_paths=["~/.codeium/mcp.json"],
           aliases=["codeium"],
           by_os={
               "windows": {"app_bundles": ["%LOCALAPPDATA%\\Programs\\Codeium"], "commands": ["codeium"],
                           "config_paths": ["%USERPROFILE%\\.codeium\\mcp.json"]},
               "linux": {"app_bundles": [], "commands": ["codeium"],
                         "config_paths": ["~/.codeium/mcp.json"]},
           }),
    _entry("Reasonix", type_="AI Agent",
           app_bundles=["/Applications/Reasonix.app"], commands=["reasonix"],
           config_paths=["~/.reasonix/config.toml"], skills_path="~/.reasonix/skills",
           mcp_config_path="~/.reasonix/config.toml", mcp_format="reasonix_toml",
           mcp_key_path="plugins",
           aliases=["reasonix"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["reasonix"],
                           "config_paths": ["%USERPROFILE%\\.reasonix\\config.toml"], "skills_path": "%USERPROFILE%\\.reasonix\\skills",
                           "mcp_config_path": "%USERPROFILE%\\.reasonix\\config.toml"},
               "linux": {"app_bundles": [], "commands": ["reasonix"],
                         "config_paths": ["~/.reasonix/config.toml"], "skills_path": "~/.reasonix/skills",
                         "mcp_config_path": "~/.reasonix/config.toml"},
           }),
    _entry("Hermes Agent", type_="AI Agent",
           commands=["hermes"], config_paths=["~/.hermes/config.yaml"],
           skills_path="~/.agents/skills",
           mcp_config_path="~/.hermes/config.yaml", mcp_format="yaml",
           mcp_key_path="mcp_servers",
           aliases=["hermes", "hermes-agent"],
           by_os={
               "windows": {"app_bundles": [], "commands": ["hermes"],
                           "config_paths": ["%USERPROFILE%\\.hermes\\config.yaml"], "skills_path": "%USERPROFILE%\\.agents\\skills",
                           "mcp_config_path": "%USERPROFILE%\\.hermes\\config.yaml"},
               "linux": {"app_bundles": [], "commands": ["hermes"],
                         "config_paths": ["~/.hermes/config.yaml"], "skills_path": "~/.agents/skills",
                         "mcp_config_path": "~/.hermes/config.yaml"},
           }),
]

